<?php

include_once('ca_staff.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_staff_perm() {
  return array('edit general settings');
}

/**
 * Implementation of hook_menu().
 */
function ca_staff_menu() {
  $items['admin/settings/ca_staff'] = array(
    'title' => 'Context Admin: Staff',
    'description' => 'Change the look and feel of ca_staff module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_staff_admin_settings_form'),
    'access arguments' => array('edit general settings'),
    'file' => 'ca_staff.admin.inc',
    'file path' => drupal_get_path('module', 'ca_staff') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function ca_staff_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implementation of hook_ctools_render_alter().
 */
function ca_staff_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask) {
  if ($subtask['name'] == 'ca_staff' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_staff') . "/css/ca_staff.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_staff_views_pre_render(&$view) {
  if ($view->name == 'ca_staff') {
    drupal_add_css(drupal_get_path('module', 'ca_staff') . "/css/ca_staff.css", 'module', 'all', FALSE);
  }
}
